cat models/bagging_clas_model=SVM_t=10_m=1000/log.txt 
cat models/bagging_clas_model=SVM_t=25_m=1000/log.txt 
cat models/bagging_clas_model=SVM_t=50_m=1000/log.txt 
cat models/bagging_clas_model=SVM_t=10_m=3000/log.txt 
cat models/bagging_clas_model=SVM_t=25_m=3000/log.txt 
cat models/bagging_clas_model=SVM_t=50_m=3000/log.txt 
cat models/bagging_clas_model=DecisionTree_t=10_m=1000/log.txt 
cat models/bagging_clas_model=DecisionTree_t=25_m=1000/log.txt 
cat models/bagging_clas_model=DecisionTree_t=50_m=1000/log.txt 
cat models/bagging_clas_model=DecisionTree_t=10_m=3000/log.txt 
cat models/bagging_clas_model=DecisionTree_t=25_m=3000/log.txt 
cat models/bagging_clas_model=DecisionTree_t=50_m=3000/log.txt 
cat models/bagging_regr_model=SVM_t=10_m=1000/log.txt 
cat models/bagging_regr_model=SVM_t=25_m=1000/log.txt 
cat models/bagging_regr_model=SVM_t=50_m=1000/log.txt 
cat models/bagging_regr_model=SVM_t=10_m=3000/log.txt 
cat models/bagging_regr_model=SVM_t=25_m=3000/log.txt 
cat models/bagging_regr_model=SVM_t=50_m=3000/log.txt 
cat models/bagging_regr_model=DecisionTree_t=10_m=1000/log.txt 
cat models/bagging_regr_model=DecisionTree_t=25_m=1000/log.txt 
cat models/bagging_regr_model=DecisionTree_t=50_m=1000/log.txt 
cat models/bagging_regr_model=DecisionTree_t=10_m=3000/log.txt 
cat models/bagging_regr_model=DecisionTree_t=25_m=3000/log.txt 
cat models/bagging_regr_model=DecisionTree_t=50_m=3000/log.txt 
cat models/adaboostm1_model=SVM_t=5/log.txt 
cat models/adaboostm1_model=SVM_t=10/log.txt 
cat models/adaboostm1_model=SVM_t=15/log.txt 
cat models/adaboostm1_model=SVM_t=20/log.txt 
cat models/adaboostm1_model=SVM_t=25/log.txt 
cat models/adaboostm1_model=SVM_t=30/log.txt 
cat models/adaboostm1_model=DecisionTree_t=5/log.txt 
cat models/adaboostm1_model=DecisionTree_t=10/log.txt 
cat models/adaboostm1_model=DecisionTree_t=15/log.txt 
cat models/adaboostm1_model=DecisionTree_t=20/log.txt 
cat models/adaboostm1_model=DecisionTree_t=25/log.txt 
cat models/adaboostm1_model=DecisionTree_t=30/log.txt 
