cat main.py --config models/bagging_clas;model=SVM;t=10;m=1000/log.txt 
cat main.py --config models/bagging_clas;model=SVM;t=25;m=1000/log.txt 
cat main.py --config models/bagging_clas;model=SVM;t=50;m=1000/log.txt 
cat main.py --config models/bagging_clas;model=SVM;t=10;m=3000/log.txt 
cat main.py --config models/bagging_clas;model=SVM;t=25;m=3000/log.txt 
cat main.py --config models/bagging_clas;model=SVM;t=50;m=3000/log.txt 
cat main.py --config models/bagging_clas;model=DecisionTree;t=10;m=1000/log.txt 
cat main.py --config models/bagging_clas;model=DecisionTree;t=25;m=1000/log.txt 
cat main.py --config models/bagging_clas;model=DecisionTree;t=50;m=1000/log.txt 
cat main.py --config models/bagging_clas;model=DecisionTree;t=10;m=3000/log.txt 
cat main.py --config models/bagging_clas;model=DecisionTree;t=25;m=3000/log.txt 
cat main.py --config models/bagging_clas;model=DecisionTree;t=50;m=3000/log.txt 
cat main.py --config models/bagging_regr;model=SVM;t=10;m=1000/log.txt 
cat main.py --config models/bagging_regr;model=SVM;t=25;m=1000/log.txt 
cat main.py --config models/bagging_regr;model=SVM;t=50;m=1000/log.txt 
cat main.py --config models/bagging_regr;model=SVM;t=10;m=3000/log.txt 
cat main.py --config models/bagging_regr;model=SVM;t=25;m=3000/log.txt 
cat main.py --config models/bagging_regr;model=SVM;t=50;m=3000/log.txt 
cat main.py --config models/bagging_regr;model=DecisionTree;t=10;m=1000/log.txt 
cat main.py --config models/bagging_regr;model=DecisionTree;t=25;m=1000/log.txt 
cat main.py --config models/bagging_regr;model=DecisionTree;t=50;m=1000/log.txt 
cat main.py --config models/bagging_regr;model=DecisionTree;t=10;m=3000/log.txt 
cat main.py --config models/bagging_regr;model=DecisionTree;t=25;m=3000/log.txt 
cat main.py --config models/bagging_regr;model=DecisionTree;t=50;m=3000/log.txt 
cat main.py --config models/adaboostm1;model=SVM;t=5/log.txt 
cat main.py --config models/adaboostm1;model=SVM;t=10/log.txt 
cat main.py --config models/adaboostm1;model=SVM;t=15/log.txt 
cat main.py --config models/adaboostm1;model=SVM;t=20/log.txt 
cat main.py --config models/adaboostm1;model=SVM;t=25/log.txt 
cat main.py --config models/adaboostm1;model=SVM;t=30/log.txt 
cat main.py --config models/adaboostm1;model=DecisionTree;t=5/log.txt 
cat main.py --config models/adaboostm1;model=DecisionTree;t=10/log.txt 
cat main.py --config models/adaboostm1;model=DecisionTree;t=15/log.txt 
cat main.py --config models/adaboostm1;model=DecisionTree;t=20/log.txt 
cat main.py --config models/adaboostm1;model=DecisionTree;t=25/log.txt 
cat main.py --config models/adaboostm1;model=DecisionTree;t=30/log.txt 
