python3 main.py --config config/rating/release/bagging_clas_model=SVM_t=10_m=1000.json 
python3 main.py --config config/rating/release/bagging_clas_model=SVM_t=25_m=1000.json 
python3 main.py --config config/rating/release/bagging_clas_model=SVM_t=50_m=1000.json 
python3 main.py --config config/rating/release/bagging_clas_model=SVM_t=10_m=3000.json 
python3 main.py --config config/rating/release/bagging_clas_model=SVM_t=25_m=3000.json 
python3 main.py --config config/rating/release/bagging_clas_model=SVM_t=50_m=3000.json 
python3 main.py --config config/rating/release/bagging_clas_model=DecisionTree_t=10_m=1000.json 
python3 main.py --config config/rating/release/bagging_clas_model=DecisionTree_t=25_m=1000.json 
python3 main.py --config config/rating/release/bagging_clas_model=DecisionTree_t=50_m=1000.json 
python3 main.py --config config/rating/release/bagging_clas_model=DecisionTree_t=10_m=3000.json 
python3 main.py --config config/rating/release/bagging_clas_model=DecisionTree_t=25_m=3000.json 
python3 main.py --config config/rating/release/bagging_clas_model=DecisionTree_t=50_m=3000.json 
python3 main.py --config config/rating/release/bagging_regr_model=SVM_t=10_m=1000.json 
python3 main.py --config config/rating/release/bagging_regr_model=SVM_t=25_m=1000.json 
python3 main.py --config config/rating/release/bagging_regr_model=SVM_t=50_m=1000.json 
python3 main.py --config config/rating/release/bagging_regr_model=SVM_t=10_m=3000.json 
python3 main.py --config config/rating/release/bagging_regr_model=SVM_t=25_m=3000.json 
python3 main.py --config config/rating/release/bagging_regr_model=SVM_t=50_m=3000.json 
python3 main.py --config config/rating/release/bagging_regr_model=DecisionTree_t=10_m=1000.json 
python3 main.py --config config/rating/release/bagging_regr_model=DecisionTree_t=25_m=1000.json 
python3 main.py --config config/rating/release/bagging_regr_model=DecisionTree_t=50_m=1000.json 
python3 main.py --config config/rating/release/bagging_regr_model=DecisionTree_t=10_m=3000.json 
python3 main.py --config config/rating/release/bagging_regr_model=DecisionTree_t=25_m=3000.json 
python3 main.py --config config/rating/release/bagging_regr_model=DecisionTree_t=50_m=3000.json 
python3 main.py --config config/rating/release/adaboostm1_clas_model=SVM_t=5.json 
python3 main.py --config config/rating/release/adaboostm1_clas_model=SVM_t=10.json 
python3 main.py --config config/rating/release/adaboostm1_clas_model=SVM_t=15.json 
python3 main.py --config config/rating/release/adaboostm1_clas_model=SVM_t=20.json 
python3 main.py --config config/rating/release/adaboostm1_clas_model=SVM_t=25.json 
python3 main.py --config config/rating/release/adaboostm1_clas_model=SVM_t=30.json 
python3 main.py --config config/rating/release/adaboostm1_clas_model=DecisionTree_t=5.json 
python3 main.py --config config/rating/release/adaboostm1_clas_model=DecisionTree_t=10.json 
python3 main.py --config config/rating/release/adaboostm1_clas_model=DecisionTree_t=15.json 
python3 main.py --config config/rating/release/adaboostm1_clas_model=DecisionTree_t=20.json 
python3 main.py --config config/rating/release/adaboostm1_clas_model=DecisionTree_t=25.json 
python3 main.py --config config/rating/release/adaboostm1_clas_model=DecisionTree_t=30.json 
python3 main.py --config config/rating/release/adaboostm1_regr_model=SVM_t=5.json 
python3 main.py --config config/rating/release/adaboostm1_regr_model=SVM_t=10.json 
python3 main.py --config config/rating/release/adaboostm1_regr_model=SVM_t=15.json 
python3 main.py --config config/rating/release/adaboostm1_regr_model=SVM_t=20.json 
python3 main.py --config config/rating/release/adaboostm1_regr_model=SVM_t=25.json 
python3 main.py --config config/rating/release/adaboostm1_regr_model=SVM_t=30.json 
python3 main.py --config config/rating/release/adaboostm1_regr_model=DecisionTree_t=5.json 
python3 main.py --config config/rating/release/adaboostm1_regr_model=DecisionTree_t=10.json 
python3 main.py --config config/rating/release/adaboostm1_regr_model=DecisionTree_t=15.json 
python3 main.py --config config/rating/release/adaboostm1_regr_model=DecisionTree_t=20.json 
python3 main.py --config config/rating/release/adaboostm1_regr_model=DecisionTree_t=25.json 
python3 main.py --config config/rating/release/adaboostm1_regr_model=DecisionTree_t=30.json 
