python3 main.py --config config/rating/release/bagging_clas;model=SVM;t=10;m=1000.json 
python3 main.py --config config/rating/release/bagging_clas;model=SVM;t=25;m=1000.json 
python3 main.py --config config/rating/release/bagging_clas;model=SVM;t=50;m=1000.json 
python3 main.py --config config/rating/release/bagging_clas;model=SVM;t=10;m=3000.json 
python3 main.py --config config/rating/release/bagging_clas;model=SVM;t=25;m=3000.json 
python3 main.py --config config/rating/release/bagging_clas;model=SVM;t=50;m=3000.json 
python3 main.py --config config/rating/release/bagging_clas;model=DecisionTree;t=10;m=1000.json 
python3 main.py --config config/rating/release/bagging_clas;model=DecisionTree;t=25;m=1000.json 
python3 main.py --config config/rating/release/bagging_clas;model=DecisionTree;t=50;m=1000.json 
python3 main.py --config config/rating/release/bagging_clas;model=DecisionTree;t=10;m=3000.json 
python3 main.py --config config/rating/release/bagging_clas;model=DecisionTree;t=25;m=3000.json 
python3 main.py --config config/rating/release/bagging_clas;model=DecisionTree;t=50;m=3000.json 
python3 main.py --config config/rating/release/bagging_regr;model=SVM;t=10;m=1000.json 
python3 main.py --config config/rating/release/bagging_regr;model=SVM;t=25;m=1000.json 
python3 main.py --config config/rating/release/bagging_regr;model=SVM;t=50;m=1000.json 
python3 main.py --config config/rating/release/bagging_regr;model=SVM;t=10;m=3000.json 
python3 main.py --config config/rating/release/bagging_regr;model=SVM;t=25;m=3000.json 
python3 main.py --config config/rating/release/bagging_regr;model=SVM;t=50;m=3000.json 
python3 main.py --config config/rating/release/bagging_regr;model=DecisionTree;t=10;m=1000.json 
python3 main.py --config config/rating/release/bagging_regr;model=DecisionTree;t=25;m=1000.json 
python3 main.py --config config/rating/release/bagging_regr;model=DecisionTree;t=50;m=1000.json 
python3 main.py --config config/rating/release/bagging_regr;model=DecisionTree;t=10;m=3000.json 
python3 main.py --config config/rating/release/bagging_regr;model=DecisionTree;t=25;m=3000.json 
python3 main.py --config config/rating/release/bagging_regr;model=DecisionTree;t=50;m=3000.json 
python3 main.py --config config/rating/release/adaboostm1;model=SVM;t=5.json 
python3 main.py --config config/rating/release/adaboostm1;model=SVM;t=10.json 
python3 main.py --config config/rating/release/adaboostm1;model=SVM;t=15.json 
python3 main.py --config config/rating/release/adaboostm1;model=SVM;t=20.json 
python3 main.py --config config/rating/release/adaboostm1;model=SVM;t=25.json 
python3 main.py --config config/rating/release/adaboostm1;model=SVM;t=30.json 
python3 main.py --config config/rating/release/adaboostm1;model=DecisionTree;t=5.json 
python3 main.py --config config/rating/release/adaboostm1;model=DecisionTree;t=10.json 
python3 main.py --config config/rating/release/adaboostm1;model=DecisionTree;t=15.json 
python3 main.py --config config/rating/release/adaboostm1;model=DecisionTree;t=20.json 
python3 main.py --config config/rating/release/adaboostm1;model=DecisionTree;t=25.json 
python3 main.py --config config/rating/release/adaboostm1;model=DecisionTree;t=30.json 
